/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/P6RoUNieH0P
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/presentation/components/ui/button";
import { Input } from "@/presentation/components/ui/input";
import Link from "next/link";
import {
  Avatar,
  AvatarImage,
  AvatarFallback,
} from "@/presentation/components/ui/avatar";
import {
  PhoneIcon,
  PlusIcon,
  SearchIcon,
  SendIcon,
  VideoIcon,
} from "lucide-react";

export function Chat() {
  return (
    <div className="flex h-screen w-full max-w-6xl mx-auto">
      <div className="border-r w-72 bg-muted/20 p-4">
        <div className="flex items-center justify-between mb-4">
          <div className="text-lg font-bold">Chats</div>
          <Button variant="ghost" size="icon" className="rounded-full">
            <PlusIcon className="h-5 w-5" />
            <span className="sr-only">New Chat</span>
          </Button>
        </div>
        <div className="relative">
          <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            type="search"
            placeholder="Search chats..."
            className="w-full rounded-lg bg-background pl-8 h-9"
          />
        </div>
        <div className="mt-4 space-y-2">
          <Link
            href="#"
            className="flex items-center gap-3 p-2 rounded-lg hover:bg-muted/50 bg-muted"
            prefetch={false}
          >
            <Avatar className="border w-10 h-10">
              <AvatarImage src="/placeholder-user.jpg" alt="Image" />
              <AvatarFallback>OM</AvatarFallback>
            </Avatar>
            <div className="grid gap-0.5">
              <p className="text-sm font-medium leading-none">Sofia Davis</p>
              <p className="text-xs text-muted-foreground">
                Hey there! How are you?
              </p>
            </div>
          </Link>
          <Link
            href="#"
            className="flex items-center gap-3 p-2 rounded-lg hover:bg-muted/50"
            prefetch={false}
          >
            <Avatar className="border w-10 h-10">
              <AvatarImage src="/placeholder-user.jpg" alt="Alex's Image" />
              <AvatarFallback>AJ</AvatarFallback>
            </Avatar>
            <div className="grid gap-0.5">
              <p className="text-sm font-medium leading-none">Alex Johnson</p>
              <p className="text-xs text-muted-foreground">
                Just finished a great book! 📚
              </p>
            </div>
          </Link>
          <Link
            href="#"
            className="flex items-center gap-3 p-2 rounded-lg hover:bg-muted/50"
            prefetch={false}
          >
            <Avatar className="border w-10 h-10">
              <AvatarImage src="/placeholder-user.jpg" alt="Maria's Image" />
              <AvatarFallback>MG</AvatarFallback>
            </Avatar>
            <div className="grid gap-0.5">
              <p className="text-sm font-medium leading-none">Maria Gonzalez</p>
              <p className="text-xs text-muted-foreground">
                Excited for the weekend!
              </p>
            </div>
          </Link>
        </div>
      </div>
      <div className="flex-1 flex flex-col">
        <div className="border-b p-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Avatar className="border w-10 h-10">
              <AvatarImage src="/placeholder-user.jpg" alt="Image" />
              <AvatarFallback>OM</AvatarFallback>
            </Avatar>
            <div className="grid gap-0.5">
              <p className="text-sm font-medium leading-none">Sofia Davis</p>
              <p className="text-xs text-muted-foreground">Active 2h ago</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="icon">
              <PhoneIcon className="h-4 w-4" />
              <span className="sr-only">Call</span>
            </Button>
            <Button variant="ghost" size="icon">
              <VideoIcon className="h-4 w-4" />
              <span className="sr-only">Video call</span>
            </Button>
          </div>
        </div>
        <div className="flex-1 overflow-y-auto p-4 grid gap-4">
          <div className="flex w-max max-w-[65%] flex-col gap-2 rounded-full px-4 py-2 text-sm ml-auto bg-primary text-primary-foreground">
            Hey hope you're doing well! We should catch up sometime soon. 🙏
          </div>
          <div className="flex w-max max-w-[65%] flex-col gap-2 rounded-full px-4 py-2 text-sm bg-muted">
            Sure! I'm free this weekend if you want to grab a coffee.
          </div>
          <div className="flex w-max max-w-[65%] flex-col gap-2 rounded-xl overflow-hidden text-sm ml-auto">
            <img
              src="/placeholder.svg"
              alt="photo"
              width={200}
              height={150}
              className="object-cover"
              style={{ aspectRatio: "200/150", objectFit: "cover" }}
            />
          </div>
          <div className="flex w-max max-w-[65%] flex-col gap-2 rounded-full px-4 py-2 text-sm ml-auto bg-primary text-primary-foreground">
            Sounds good! Let's meet at the Starbucks on 5th Ave.
          </div>
          <div className="flex w-max max-w-[65%] flex-col gap-2 rounded-full px-4 py-2 text-sm bg-muted">
            I'll message you on Saturday.
          </div>
        </div>
        <div className="border-t">
          <form className="flex w-full items-center space-x-2 p-3">
            <Input
              id="message"
              placeholder="Type your message..."
              className="flex-1"
              autoComplete="off"
            />
            <Button type="submit" size="icon">
              <SendIcon className="h-4 w-4" />
              <span className="sr-only">Send</span>
            </Button>
          </form>
        </div>
      </div>
    </div>
  );
}

// function PhoneIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
//     </svg>
//   )
// }

// function PlusIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M5 12h14" />
//       <path d="M12 5v14" />
//     </svg>
//   )
// }

// function SearchIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <circle cx="11" cy="11" r="8" />
//       <path d="m21 21-4.3-4.3" />
//     </svg>
//   )
// }

// function SendIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="m22 2-7 20-4-9-9-4Z" />
//       <path d="M22 2 11 13" />
//     </svg>
//   )
// }

// function VideoIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />
//       <rect x="2" y="6" width="14" height="12" rx="2" />
//     </svg>
//   )
// }
